"""
Django settings for VerManager project.

Generated by 'django-admin startproject' using Django 2.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '6uler=ay#_%8&f5d!_8ktc^la6i096g&q%_w$x(#7%1v1u3)hc'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

HOST = os.environ.get('ALLOWED_HOST')
if HOST is None:
    HOST = 'localhost'
ALLOWED_HOSTS = [HOST]


# Application definition

INSTALLED_APPS = [
    'manager.apps.ManagerConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'channels',
    'client.apps.ClientConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'VerManager.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'VerManager.wsgi.application'
ASGI_APPLICATION = "VerManager.asgi.application"


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

vermng_mysql_db = os.environ.get('VERMNG_MYSQL_NAME')
vermng_mysql_user = os.environ.get('VERMNG_MYSQL_USER')
vermng_mysql_passwd = os.environ.get('VERMNG_MYSQL_PASSWD')
vermng_mysql_host = os.environ.get('VERMNG_MYSQL_HOST')
vermng_mysql_port = os.environ.get('VERMNG_MYSQL_PORT')


def mysql_param_from_env(varName, defVal):
    val = os.environ.get(varName)
    if val is None:
        return defVal
    else:
        return val


def from_env_or_default(varName, defVal):
    return mysql_param_from_env(varName, defVal)


CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [(
                from_env_or_default("VERMNG_REDIS_ADDR", "127.0.0.1"),
                6379
            )],
        },
    },
}


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': mysql_param_from_env('VERMNG_MYSQL_NAME','vermanager'),
        'USER': mysql_param_from_env('VERMNG_MYSQL_USER', 'verM'),
        'PASSWORD': mysql_param_from_env('VERMNG_MYSQL_PASSWD', '123456'),
        'HOST': mysql_param_from_env('VERMNG_MYSQL_HOST', '127.0.0.1'),
        'PORT': mysql_param_from_env('VERMNG_MYSQL_PORT', '3306')
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

DATA_URL = '/data/'
STATIC_URL = '/static/'
STATIC_ROOT = '/home/ayden/Codebase/VerManager/static/'
STATICFILES_DIRS = (
    '/home/ayden/Codebase/VerManager/manager/static/',
    '/home/ayden/Codebase/VerManager/WorkSpace/data/'
)

REQUIRE_BASE_URL = "./"
REQUIRE_JS = "lib/require.js"
